# 超参数配置
worker_process:
  pass 
  
# 数据层线程  
# 缓存池配置  
# 最少数据(year)    
# 最大数据(year)  
# 检测间隔  
data_thread:
  min_year: 1 # 仅有1年数据后，获取数据  
  max_year: 2 # 每次获取，使得存在至少2年数据   
  check_interval: 10 # 检测间隔(s)  
